/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_aj;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontPosture;

/**
 *
 * @author ANDY
 */
public class diccionario extends javax.swing.JPanel {

    /**
     * Creates new form diccionario2
     */
    public diccionario() {
        initComponents();
        Procedimientos.sololetras2(papel);
        Procedimientos.quitarspacio2(papel);
    }
    public static String Cadena;
    int cp = 0;
    Character espacio;
    int comas = 0;
    String palabra = "";
    int id = 1;
    
    Icon img1 = new ImageIcon(getClass().getResource("/img/spain.png"));
    Icon img2 = new ImageIcon(getClass().getResource("/img/ing.png"));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Idioma1 = new javax.swing.JLabel();
        idm2 = new javax.swing.JLabel();
        bande1 = new javax.swing.JLabel();
        bande2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        papel = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablero = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        Sugeridolbl = new javax.swing.JLabel();
        verpa1 = new javax.swing.JButton();
        NoEncriptar = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flip_horizontal-32.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Idioma1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Idioma1.setForeground(new java.awt.Color(31, 109, 199));
        Idioma1.setText("Español");

        idm2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idm2.setForeground(new java.awt.Color(31, 109, 199));
        idm2.setText("Ingles");

        bande1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spain.png"))); // NOI18N

        bande2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ing.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(bande1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Idioma1)
                .addGap(140, 140, 140)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(idm2)
                .addGap(18, 18, 18)
                .addComponent(bande2)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bande2)
                    .addComponent(idm2)
                    .addComponent(jButton1)
                    .addComponent(Idioma1)
                    .addComponent(bande1))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 40));

        papel.setColumns(20);
        papel.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        papel.setRows(5);
        papel.setBorder(null);
        papel.setCaretColor(new java.awt.Color(204, 204, 204));
        papel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                papelKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                papelEnTiempoReal(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                papelKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(papel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 310, -1));

        tablero.setEditable(false);
        tablero.setColumns(20);
        tablero.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        tablero.setRows(5);
        tablero.setBorder(null);
        tablero.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tableroInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(tablero);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 310, 130));

        jLabel3.setText("Porfavor ingrese las palabras separadas por \",\"");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel1.add(Sugeridolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 370, 20));

        verpa1.setBackground(new java.awt.Color(239, 191, 0));
        verpa1.setForeground(new java.awt.Color(255, 255, 255));
        verpa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Masks.png"))); // NOI18N
        verpa1.setText("Desencriptar");
        verpa1.setBorder(null);
        verpa1.setBorderPainted(false);
        verpa1.setFocusPainted(false);
        verpa1.setPreferredSize(new java.awt.Dimension(116, 24));
        verpa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verpa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verpa1MouseExited(evt);
            }
        });
        verpa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verpa1ActionPerformed(evt);
            }
        });
        jPanel1.add(verpa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 160, -1));
        jPanel1.add(NoEncriptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 370, 20));

        error.setForeground(new java.awt.Color(255, 0, 51));
        error.setText(" ");
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        papel.setText("");
        tablero.setText("");
        if (Idioma1.getText().equals("Español")) {
            Idioma1.setText("Ingles");
            idm2.setText("Español");
            bande2.setIcon(img1);
            bande1.setIcon(img2);
            id = 2;

        } else {
            idm2.setText("Ingles");
            Idioma1.setText("Español");
            bande1.setIcon(img1);
            bande2.setIcon(img2);
            id = 1;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void papelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_papelKeyPressed

    }//GEN-LAST:event_papelKeyPressed

    private void papelEnTiempoReal(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_papelEnTiempoReal
        comas = 0;//reinicio lavariable para saber el numero verdadero de comas que hay cada vez que se escribe
        error.setText("");
        for (int i = 0; i < papel.getText().length(); i++) {
            if (papel.getText().substring(i, i + 1).equals(",")) {
                comas++;
            }
        }
    
        //EVENTO PARA QUE QUEDE LINDO
        Cadena = papel.getText().toLowerCase();
String def="";
String def1="";
        String[] ListaDePalabras = Procedimientos.ListaDePalabrasAtraducir(Cadena);
        if (comas < 4) {
            String Traduccion = Procedimientos.mostrarTraduccion(ListaDePalabras);
            String traducido[]=Procedimientos.ListaDePalabrasAtraducir(Traduccion);
              
            if (Cadena.equals(Traduccion) || Traduccion.equals(Cadena.substring(0, Cadena.length() - 1))) {
                tablero.setText(Traduccion);
                if ("".equals(papel.getText())) {
                    NoEncriptar.setText("");
                } else {
                    NoEncriptar.setText("La palabra " + Cadena + " No se puede encriptar");
                }

            } else {
                  for (int i = 0; i < traducido.length; i++) {
                  def1=traducido[i];  
                  if (traducido[i].equals(ListaDePalabras[i])) {
                       
                               if (i==0) {
                                  
                          def=def1;  
                      System.out.println(def+"");
                        }else{
                                   
                        def=def+","+def1;
                                   System.out.println(def+"");
                              }
  
                    }else{
                     if (i==0) {
                             System.out.println(""+Procedimientos.CifradoHill(def1));
                         System.out.println(""+ Procedimientos.cifrarvigenere(Procedimientos.CifradoHill(def1),"abc"));
                   
                          def= Procedimientos.binarios(Procedimientos.cifrarvigenere(Procedimientos.CifradoHill(def1),"abc")); 
                        }else{
                               def=  def +"," +Procedimientos.binarios(Procedimientos.cifrarvigenere(Procedimientos.CifradoHill(def1),"abc"));
                   
                     
                     }
                    }
                }
                tablero.setText(def);
//                 SOLANO AQUI VAN LOS CIFRADOS OJO YA SABES QUE FALTA LA COMA CON HILL y Lo de cifrar palabra por palabra  
                      
               
                NoEncriptar.setText("");
            }
        } else {
            error.setText("Maximo 4 palabras a Buscar ");
            papel.setText(papel.getText().substring(0, papel.getText().length() - 1));

        }
    }//GEN-LAST:event_papelEnTiempoReal

    private void verpa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verpa1MouseEntered

        verpa1.setBackground(new Color(255, 168, 2));
    }//GEN-LAST:event_verpa1MouseEntered

    private void verpa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verpa1MouseExited
        verpa1.setBackground(new Color(239, 191, 0));
    }//GEN-LAST:event_verpa1MouseExited

    private void verpa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verpa1ActionPerformed
        //ACA LLAMAS EL METODO DE DESCIFRADOHILL
        String def1="";
        String def="";
        
        String[] encrip=Procedimientos.ListaDePalabrasAtraducir(tablero.getText());
        String [] desencrip=Procedimientos.ListaDePalabrasAtraducir(papel.getText());
           for (int i = 0; i < desencrip.length; i++) {
                  def1=encrip[i];  
                  if (encrip[i].equals(desencrip[i])) {
                       
                               if (i==0) {
                                  
                          def=def1;  
                      System.out.println(def+"");
                        }else{
                                   
                        def=def+","+def1;
                              
                              }
  
                    }else{
                     if (i==0) {
                               def= Procedimientos.DescifradoHill(Procedimientos.decivigenre(Procedimientos.binarioastring(def1),"abc")); 
                     if ("x".equals(def.substring(def.length() - 1, def.length())) && Procedimientos.xAdd == true) {
                             
                             def=def.substring(0, def.length() - 1);
                                    Procedimientos.xAdd = false;
                    }   
                     
                     
                     
                     }else{
                         def1=Procedimientos.DescifradoHill(Procedimientos.decivigenre(Procedimientos.binarioastring(def1),"abc"));
 
                         if ("x".equals(def1.substring(def1.length() - 1, def1.length())) && Procedimientos.xAdd == true) {
                             
                             def1=def1.substring(0, def1.length() - 1);
                                    Procedimientos.xAdd = false;
                    }
                               def=  def +"," +  def1;   
                     
                     }
                    }
                }
tablero.setText(def);
       
     

    }//GEN-LAST:event_verpa1ActionPerformed

    private void tableroInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tableroInputMethodTextChanged

        if (tablero.getText().length() > 8) {

            tablero.setFont(new java.awt.Font("Monospaced", 1, 10));

        }
    }//GEN-LAST:event_tableroInputMethodTextChanged

    private void papelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_papelKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_papelKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Idioma1;
    public static javax.swing.JLabel NoEncriptar;
    public static javax.swing.JLabel Sugeridolbl;
    private javax.swing.JLabel bande1;
    private javax.swing.JLabel bande2;
    private javax.swing.JLabel error;
    private javax.swing.JLabel idm2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea papel;
    public static javax.swing.JTextArea tablero;
    private javax.swing.JButton verpa1;
    // End of variables declaration//GEN-END:variables
}
