/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_aj;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author juans_000
 */
public class Diccionario_Añadir extends javax.swing.JFrame {

    /**
     * Creates new form Diccionario_Añadir
     */
    int x,y;
    public Diccionario_Añadir() {
        initComponents();
        Palabras_Limite.setText("Palabras " + inicio.palabras + "/" + Diccionario_Limite.Limite);
        this.setLocationRelativeTo(null);
           Procedimientos.sololetras(PalabraEsptxt);
           Procedimientos.sololetras(PalabraIngtxt);
            Procedimientos.quitarspacio(PalabraEsptxt);
           Procedimientos.quitarspacio(PalabraIngtxt);
           

    }
    public static String[] PalabrasEsp = new String[100];
    public static String[] PalabrasIng = new String[100];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Palabras_Limite = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PalabraIngtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PalabraEsptxt = new javax.swing.JTextField();
        AñadirPalabraBTN = new javax.swing.JButton();
        cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(31, 109, 199));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add-New.png"))); // NOI18N
        jLabel1.setText("Añadir");

        Palabras_Limite.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Palabras_Limite.setForeground(new java.awt.Color(255, 255, 255));
        Palabras_Limite.setText("PALABRAS 0/0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addComponent(Palabras_Limite)
                .addContainerGap(540, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Palabras_Limite))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 40));

        jLabel2.setText("Ingrese la palabra que desea añadir en Ingles");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        PalabraIngtxt.setBorder(null);
        PalabraIngtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PalabraIngtxtKeyPressed(evt);
            }
        });
        jPanel1.add(PalabraIngtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 310, -1));

        jLabel3.setText("Ingrese la palabra que desea añadir en Español");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        PalabraEsptxt.setBorder(null);
        PalabraEsptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PalabraEsptxtKeyPressed(evt);
            }
        });
        jPanel1.add(PalabraEsptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 310, -1));

        AñadirPalabraBTN.setBackground(new java.awt.Color(239, 191, 0));
        AñadirPalabraBTN.setForeground(new java.awt.Color(255, 255, 255));
        AñadirPalabraBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        AñadirPalabraBTN.setText("Añadir");
        AñadirPalabraBTN.setBorder(null);
        AñadirPalabraBTN.setBorderPainted(false);
        AñadirPalabraBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirPalabraBTNActionPerformed(evt);
            }
        });
        jPanel1.add(AñadirPalabraBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 110, 30));

        cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Previous.png"))); // NOI18N
        cerrar.setText("X");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 25, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirPalabraBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirPalabraBTNActionPerformed
        Procedimientos.AgregarPalabra(PalabraEsptxt.getText(), PalabraIngtxt.getText()); //SUBRUTINA PA AGREGAR
        PalabraEsptxt.setText("");
        PalabraIngtxt.setText("");
        Palabras_Limite.setText("Palabras " + inicio.palabras + "/" + Diccionario_Limite.Limite);
         
    }//GEN-LAST:event_AñadirPalabraBTNActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        new inicio().setVisible(true);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        cerrar.setForeground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        cerrar.setForeground(Color.WHITE);            // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
      x=evt.getX();
       y=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        this.setLocation(this.getLocation().x+evt.getX()-x,this.getLocation().y+evt.getY()-y);
    }//GEN-LAST:event_formMouseDragged

    private void PalabraEsptxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PalabraEsptxtKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_PalabraEsptxtKeyPressed

    private void PalabraIngtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PalabraIngtxtKeyPressed
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if (a==KeyEvent.VK_ENTER) {
            if (!PalabraEsptxt.getText().equals("")&&!PalabraIngtxt.getText().equals("")) {
               AñadirPalabraBTNActionPerformed(null ) ;
            }
        }
        
    }//GEN-LAST:event_PalabraIngtxtKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    
        
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diccionario_Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diccionario_Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diccionario_Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diccionario_Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diccionario_Añadir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirPalabraBTN;
    private javax.swing.JTextField PalabraEsptxt;
    private javax.swing.JTextField PalabraIngtxt;
    private javax.swing.JLabel Palabras_Limite;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
