/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_aj;

import java.awt.Color;

 
/**
 *
 * @author ANDY y SOLANO
 */
public class inicio extends javax.swing.JFrame {
  public static int palabras;
    int x;
    int y;
    public inicio() {

        initComponents();
        this.setSize(860, 308);
        Palabras_Limite.setText("Palabras " + inicio.palabras + "/" + Diccionario_Limite.Limite);
       // diccionario d =new diccionario();
     //Procedimientos.mjframe(jPanel1,d);
        this.setLocationRelativeTo(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        AddPalabrasBTN = new javax.swing.JButton();
        verpa = new javax.swing.JButton();
        Diccionariobtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Palabras_Limite = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(844, 222));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerSize(1);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gear.png"))); // NOI18N
        jLabel2.setText("Opciones ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPalabrasBTN.setBackground(new java.awt.Color(239, 191, 0));
        AddPalabrasBTN.setForeground(new java.awt.Color(255, 255, 255));
        AddPalabrasBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nenw.png"))); // NOI18N
        AddPalabrasBTN.setText("Añadir Palabras      ");
        AddPalabrasBTN.setBorder(null);
        AddPalabrasBTN.setBorderPainted(false);
        AddPalabrasBTN.setFocusPainted(false);
        AddPalabrasBTN.setPreferredSize(new java.awt.Dimension(116, 24));
        AddPalabrasBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddPalabrasBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddPalabrasBTNMouseExited(evt);
            }
        });
        AddPalabrasBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPalabrasBTNActionPerformed(evt);
            }
        });
        jPanel6.add(AddPalabrasBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 36));

        verpa.setBackground(new java.awt.Color(239, 191, 0));
        verpa.setForeground(new java.awt.Color(255, 255, 255));
        verpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        verpa.setText("Ver Lista Palabras  ");
        verpa.setBorder(null);
        verpa.setBorderPainted(false);
        verpa.setFocusPainted(false);
        verpa.setPreferredSize(new java.awt.Dimension(116, 24));
        verpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verpaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verpaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verpaMouseExited(evt);
            }
        });
        verpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verpaActionPerformed(evt);
            }
        });
        jPanel6.add(verpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 36));

        Diccionariobtn.setBackground(new java.awt.Color(239, 191, 0));
        Diccionariobtn.setForeground(new java.awt.Color(255, 255, 255));
        Diccionariobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Books.png"))); // NOI18N
        Diccionariobtn.setText("Mostrar Diccionario");
        Diccionariobtn.setBorder(null);
        Diccionariobtn.setBorderPainted(false);
        Diccionariobtn.setFocusPainted(false);
        Diccionariobtn.setPreferredSize(new java.awt.Dimension(116, 24));
        Diccionariobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiccionariobtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiccionariobtnMouseExited(evt);
            }
        });
        Diccionariobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiccionariobtnActionPerformed(evt);
            }
        });
        jPanel6.add(Diccionariobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 200, 36));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 140));

        jSplitPane1.setLeftComponent(jPanel4);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText(" ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jLabel5.setText(" ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 250));

        jSplitPane1.setRightComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(31, 109, 199));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DICCIONARIO LAB");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Palabras_Limite.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Palabras_Limite.setForeground(new java.awt.Color(255, 255, 255));
        Palabras_Limite.setText("PALABRAS 0/0");
        jPanel2.add(Palabras_Limite, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 11, -1, -1));

        mini.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        mini.setForeground(new java.awt.Color(255, 255, 255));
        mini.setText("−");
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMouseExited(evt);
            }
        });
        jPanel2.add(mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 20, -1));

        cerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("X");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        jPanel2.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Data-Files.png"))); // NOI18N
        jLabel4.setText(" ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPalabrasBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPalabrasBTNActionPerformed
        new Diccionario_Añadir().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddPalabrasBTNActionPerformed

    private void AddPalabrasBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPalabrasBTNMouseEntered
    AddPalabrasBTN.setBackground(new Color(255, 168, 2));
    }//GEN-LAST:event_AddPalabrasBTNMouseEntered

    private void AddPalabrasBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPalabrasBTNMouseExited
     AddPalabrasBTN.setBackground(new Color(239, 191, 0));    // TODO add your handling code here:
    }//GEN-LAST:event_AddPalabrasBTNMouseExited

    private void verpaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verpaMouseEntered
      verpa.setBackground(new Color(255, 168, 2));
    }//GEN-LAST:event_verpaMouseEntered

    private void verpaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verpaMouseExited
   verpa.setBackground(new Color(239, 191, 0));  
    }//GEN-LAST:event_verpaMouseExited

    private void verpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verpaActionPerformed
      listapalabras mostrar = new listapalabras();
      
      Procedimientos.Mtabla(listapalabras.tabla);
      Procedimientos.mjframe(jPanel1,mostrar);
      
      
    }//GEN-LAST:event_verpaActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
      System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
      this.setState(1) ;
    }//GEN-LAST:event_miniMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
       cerrar.setForeground(new Color(255, 168, 2));
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
     cerrar.setForeground(Color.WHITE);
    }//GEN-LAST:event_cerrarMouseExited

    private void miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseEntered
       mini.setForeground(new Color(255, 168, 2));
    }//GEN-LAST:event_miniMouseEntered

    private void miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseExited
       mini.setForeground(Color.WHITE);
    }//GEN-LAST:event_miniMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x=evt.getX();
       y=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        this.setLocation(this.getLocation().x+evt.getX()-x,this.getLocation().y+evt.getY()-y);

    }//GEN-LAST:event_formMouseDragged

    private void verpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verpaMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_verpaMouseClicked

    private void DiccionariobtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiccionariobtnMouseEntered
   Diccionariobtn.setBackground(new Color(255, 168, 2));
    }//GEN-LAST:event_DiccionariobtnMouseEntered

    private void DiccionariobtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiccionariobtnMouseExited
          Diccionariobtn.setBackground(new Color(239, 191, 0));
    }//GEN-LAST:event_DiccionariobtnMouseExited

    private void DiccionariobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiccionariobtnActionPerformed
        // TODO add your handling code here:
        diccionario d = new diccionario();
        Procedimientos.mjframe(jPanel1,d);
    }//GEN-LAST:event_DiccionariobtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPalabrasBTN;
    private javax.swing.JButton Diccionariobtn;
    private javax.swing.JLabel Palabras_Limite;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel mini;
    private javax.swing.JButton verpa;
    // End of variables declaration//GEN-END:variables
}
